### PR TITLE
Back navigation & Title components

### PR DESCRIPTION
**Pull request by DanielSzym**
At the moment you have to insert the props (like title name for Title component or reference for back navigation) manually. Still, better overview in the pages.

### CODE REVIEW

**Comment by yOoMarvin** [comment]
can you also add the back button to the surprise me page?

**Comment by DanielSzym** [comment]
Done.

**Comment by DanielSzym** [comment]
> can you also add the back button to the surprise me page?

Done!

**Comment by yOoMarvin** [comment]
great! What about making the back button and the title in one component?

**Comment by DanielSzym** [comment]
> great! What about making the back button and the title in one component?

Not all pages have back buttons AND a title
Examples, where there is **both**: Timeline, Hospital Stay, Notes, Surprise Me
Examples with back button **only** : Calendar, Discover

Would keep it in two separate components.

**Comment by yOoMarvin** [comment]
I think discover will not even have a back button because it's in the tab bar. And the calendar can also have a title, that shouldn't be a problem 👍

**Pull request merged**
